export const options = [
  {
    vehicle: "Economic",
    departure: "Bến xe Bản Phủ",
    destination: "Bến xe Mỹ Đình",
    timeStart: "19:30",
    timeEnd: "06:00",
    title: "Giường nằm 4X chỗ với:",
    content: [
      "Nước đóng chai miễn phí",
      "Wifi miễn phí",
      "Cổng sạc USB",
      "Bảo hiểm du lịch",
      "Phòng chờ VIP",
    ],
    blank: "9",
    price: "400.000",
  },
  {
    vehicle: "Economic",
    departure: "Bến xe Bản Phủ",
    destination: "Bến xe Mỹ Đình",
    timeStart: "19:30",
    timeEnd: "06:00",
    title: "Giường nằm 4X chỗ với:",
    content: [
      "Nước đóng chai miễn phí",
      "Wifi miễn phí",
      "Cổng sạc USB",
      "Bảo hiểm du lịch",
      "Phòng chờ VIP",
    ],
    blank: "9",
    price: "400.000",
  },
  {
    vehicle: "Economic",
    departure: "Bến xe Bản Phủ",
    destination: "Bến xe Mỹ Đình",
    timeStart: "19:30",
    timeEnd: "06:00",
    title: "Giường nằm 4X chỗ với:",
    content: [
      "Nước đóng chai miễn phí",
      "Wifi miễn phí",
      "Cổng sạc USB",
      "Bảo hiểm du lịch",
      "Phòng chờ VIP",
    ],
    blank: "9",
    price: "400.000",
  },
  {
    vehicle: "Economic",
    departure: "Bến xe Bản Phủ",
    destination: "Bến xe Mỹ Đình",
    timeStart: "19:30",
    timeEnd: "06:00",
    title: "Giường nằm 4X chỗ với:",
    content: [
      "Nước đóng chai miễn phí",
      "Wifi miễn phí",
      "Cổng sạc USB",
      "Bảo hiểm du lịch",
      "Phòng chờ VIP",
    ],
    blank: "9",
    price: "400.000",
  },
  {
    vehicle: "Economic",
    departure: "Bến xe Bản Phủ",
    destination: "Bến xe Mỹ Đình",
    timeStart: "19:30",
    timeEnd: "06:00",
    title: "Giường nằm 4X chỗ với:",
    content: [
      "Nước đóng chai miễn phí",
      "Wifi miễn phí",
      "Cổng sạc USB",
      "Bảo hiểm du lịch",
      "Phòng chờ VIP",
    ],
    blank: "9",
    price: "400.000",
  },
  {
    vehicle: "Economic",
    departure: "Bến xe Bản Phủ",
    destination: "Bến xe Mỹ Đình",
    timeStart: "19:30",
    timeEnd: "06:00",
    title: "Giường nằm 4X chỗ với:",
    content: [
      "Nước đóng chai miễn phí",
      "Wifi miễn phí",
      "Cổng sạc USB",
      "Bảo hiểm du lịch",
      "Phòng chờ VIP",
    ],
    blank: "9",
    price: "400.000",
  },
];
