import "./globals.css";
import StoreProvider from "./StoreProvider";
import { Suspense } from "react";
import Loading from "./loading";

export const metadata = {
  title: "Binford",
  description: "Binford",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
        <meta name="title" content={metadata.title} />
        <meta property="og:title" content={metadata.title} key="title" />
        <meta property="og:description" content={metadata.description} />
        <meta property="og:image" content="/logo.png" />
        {/* <meta name="url" content="https://localhost:3000" /> */}
        <title>{metadata.title}</title>
      </head>
      <body className="body relative">
        <StoreProvider>
          <Suspense fallback={<Loading />}>{children}</Suspense>
        </StoreProvider>
      </body>
    </html>
  );
}
