import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import Footer from "@/components/footer";
import StoreProvider from "./StoreProvider";

export const metadata = {
  title: "Booking App",
  description: "Booking App",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/logo.jpg" /> */}
        <meta name="title" content={metadata.title} />
        <meta property="og:title" content={metadata.title} key="title" />
        <meta property="og:description" content={metadata.description} />
        {/* <meta property="og:image" content="/logo.jpg" /> */}
        {/* <meta name="url" content="https://localhost:3000" /> */}
        <title>{metadata.title}</title>
      </head>
      <body className="body relative">
        <StoreProvider>
          <Header />
          {children}
          <Footer />
        </StoreProvider>
      </body>
    </html>
  );
}
